services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      SCRAPER_BASE_URL: http://scraper:3001
    depends_on:
      - scraper
    ports:
      - "8080:8000"

  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
    ports:
      - "3001:3001"
